### ISSUE TITLE
Auto-login broken when logged in with new added user

### ISSUE THREAD

**Issue by pranavmalvawala** [LiveChurchSolutions/ChumsApp#108]
Login works fine for the user who has created the church but once in a while when a person is given a user role and he/she tries to login, on refresh he/she will have to type credentials again! That should not happen, expected behavior is - it should remain logged in until manually logged out or token is expired.

**Comment by pranavmalvawala** [comment]
So I figured out the problem, issue is, the new user won't have any AccessApi permissions so in login response there won't be access api block and we consider user as logged in when we get the accessapi token and verify the login by calling login api with that token.

**Comment by jzongker** [comment]
I'm not sure I fully understand or if your note on the 7/15/21 is still true.  There should always be at least user JWT even if it has no church specific permissions.  Let's talk on Slack if needed.

**Comment by pranavmalvawala** [comment]
I'll check again and let you know

**Comment by jzongker** [comment]
It appears this issue has been resolved for a while.  Closing the ticket unless it recurs.
