### ISSUE TITLE
Date is off by one day

### ISSUE THREAD

**Issue by tec7z7** [LiveChurchSolutions/ChumsApp#120]
Something in the [DateHelper](https://github.com/LiveChurchSolutions/AppBase/blob/main/helpers/DateHelper.ts) class is not returning the correct date.

After editing the batch date, it always displays as one day earlier than what was set.

<img width="1139" alt="Screen Shot 2021-07-23 at 6 07 32 PM" src="https://user-images.githubusercontent.com/5470928/126849586-c5b8ed2c-8937-437c-b792-43a3dcd9490f.png">

**Comment by pranavmalvawala** [comment]
Good catch, you want to take this on @tec7z7 ?

**Comment by tec7z7** [comment]
Yeah, I'll take a look at it.
