### ISSUE TITLE
Login for new user broken

### ISSUE THREAD

**Issue by tec7z7** [LiveChurchSolutions/ChumsApp#130]
Trying to log in after registering a new user is giving me an error from the [successCallback](https://github.com/LiveChurchSolutions/ChumsApp/blob/main/src/Login.tsx#L16) function in [login.tsx](https://github.com/LiveChurchSolutions/ChumsApp/blob/main/src/Login.tsx). It appears that the `UserHelper.currentChurch` is undefined. I have also noticed that the `UserHelper.churches` is never set in the [UserHelper.selectChurch()](https://github.com/LiveChurchSolutions/AppBase/blob/main/helpers/UserHelper.ts#L42). I tried calling the `get churches/:churchId` endpoint to set it, but I am still unauthorized at that point. Also, this was done after reinitializing the databases so this is the first user on an app without any existing data.

**Comment by pranavmalvawala** [comment]
I'm gonna give it a try (after reinitializing the databases) and let you know how it goes.

**Comment by pranavmalvawala** [comment]
Update - it works alright! I pushed some changes to access api and chumsapp few hours ago I think that fixes it. So take a pull, try it and let me know if you still face an error.

**Comment by tec7z7** [comment]
I pulled and updated everything right before creating this issue but I may have missed something. I'll double check and make sure everything is up to date then try it again.

**Comment by tec7z7** [comment]
I made sure everything was up to date and then reinitialized the databases, but I still got the same error after trying to register and then log in through the ChumsApp. I also noticed that I have a `churchId` in the [UserHelper.selectChurch()](https://github.com/LiveChurchSolutions/AppBase/blob/main/helpers/UserHelper.ts#L42) function but there are no churches saved in the DB and I haven't gone through any process to create one.

<img width="1128" alt="Screen Shot 2021-09-04 at 11 14 27 AM" src="https://user-images.githubusercontent.com/5470928/132108354-b44a15c6-b52a-47ae-a703-a77db7b071f4.png">

**Comment by pranavmalvawala** [comment]
Interesting, By register, you mean you registered a user from chumsApp itself right? (not that registering from other app should be problem but let me know which one you used I may have to check it) I don't know if you know but the flow has all been updated and you can find the steps [here](https://github.com/LiveChurchSolutions/AppBase/wiki/Login-Process)

**Comment by tec7z7** [comment]
Thanks, that login process wiki is helpful. Yes, everything is done within the chumsApp. I think the issue has something to do with there being no churches available because I'm registering a new user without any existing churches. If this is the issue, is this a scenario that can't happen in production? It is still very possible that I messed something up.

**Comment by pranavmalvawala** [comment]
It can definitely happen in production for self hosting people. 

It should have worked though as registration process is deliberately separated. Last time I checked the flow flushing on access database, let me go over and flush everything and then try again.

**Comment by pranavmalvawala** [comment]
Man! I can't reproduce it. I don't why its failing for you. Do me a favor, make temp folder and clone chumsapp, accessApi, membership (latest code from main) and setup all 3 with database and then try to run.

**Comment by tec7z7** [comment]
Ok, I created a new folder and cloned the chumsApp, accessApi, and membershipApi repos and created new databases for them but I still got the same error when I tried to register a new user.

**Comment by pranavmalvawala** [comment]
Ah, then something is possibly broken. Any api is breaking or is it just the frontend?

**Comment by tec7z7** [comment]
I don't see any API errors, they are just on the frontend.

**Comment by pranavmalvawala** [comment]
Interesting, I just tried with whole new copies and it worked. Let me know how can I help. 

I've spotted another problem but it looks unrelated to your issue cause here api is throwing 401 while selecting church.

**Comment by tec7z7** [comment]
Thanks, I'll keep working on it and see what I can figure out.

**Comment by tec7z7** [comment]
It seems to be working now. The only thing that was updated was pulling the latest ChumsApp code. I don't know if or why that fixed it because the two PRs that I pulled in didn't seem to have anything to do with the login or registration processes. Thanks for the help, @pranavmalvawala

**Comment by tec7z7** [comment]
It looks like the issue was caused by running the ChumsApp and the B1App at the same time and trying to log into both in the same browser window (different tabs). I was able to log into both apps by logging into one of the apps in a normal Chrome window and the other one in an Incognito window.

**Comment by pranavmalvawala** [comment]
That's interesting, I'll check it out today.

**Comment by pranavmalvawala** [comment]
I've updated the submodule and it seems to be working now, let me know if you still face an error. Btw you may already know it but b1 app is subdomain specific just like streamingLive so its possible you tried it without a subdomain and it caused failure.
