### ISSUE TITLE
Use Church logo when available

### ISSUE THREAD

**Issue by PhotoPaul** [LiveChurchSolutions/ChumsApp#177]
How do you feel about using the specific church's logo when one is available, instead of the generic CHUMS one? This would be good for raising "ownership", but it would also make life easier to users who manage multiple churches because it would allow them, with one glance, to know which one they're currently managing (without having to click on their profile name).

![image](https://user-images.githubusercontent.com/3471804/169664781-b9576439-3cb0-42e8-b743-82c39ac83e6c.png)

**Comment by jzongker** [comment]
Yeah, I think that sounds great.  Could do the same with the AccountsApp too.  StreamingLIve and B1 already do this.

**Comment by PhotoPaul** [comment]
https://github.com/LiveChurchSolutions/ChumsApp/commit/dbf155709d186640b9b0165acc64fe14b409c647
