### ISSUE TITLE
Attendance Table is stuck in loading

### ISSUE THREAD

**Issue by luisagloria** [LiveChurchSolutions/ChumsApp#181]
#### Issue description
Attendance Table is stuck in loading in Chums App

#### Prerequisites
URL: https://app.staging.chums.org/
Browser: Chrome
User: cypress.test@chums.org
Password: password

#### Steps to reproduce the issue

1.  Login using the given credentials in the prerequisites above
2. Click Cypress Chums on the popup dialog
3. Go to the Attendance Tab

#### What's the expected result?
The Page should load without any issues
-

#### What's the actual result?
Attendance Table is stuck in loading
-

#### Additional details / screenshot
![image](https://user-images.githubusercontent.com/101709075/174474946-0b33fb08-2012-422c-a0ba-05119079c11a.png)

**Comment by jzongker** [comment]
The reporting api wasn't properly configured on dev.  The page loads correctly now.
