### ISSUE TITLE
Donations Page is stuck in loading

### ISSUE THREAD

**Issue by luisagloria** [LiveChurchSolutions/ChumsApp#182]
#### Issue description
Donations Page is stuck in loading in Chums App

#### Prerequisites
URL: https://app.staging.chums.org/
Browser: Chrome
User: cypress.test@chums.org
Password: password

#### Steps to reproduce the issue

1.  Login using the given credentials in the prerequisites above
2. Click Cypress Chums on the popup dialog
3. Go to the Donations Tab

#### What's the expected result?
The Page should load without any issues
-

#### What's the actual result?
Donations Page is stuck in loading
-

#### Additional details / screenshot
![image](https://user-images.githubusercontent.com/101709075/174475844-c3b09ddb-3d49-4100-a194-fdc2d43bcd94.png)

**Comment by jzongker** [comment]
The reporting api wasn't properly configured on dev.  The page loads correctly now.
