### ISSUE TITLE
FormSubmissionEdit is duplicated

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/ChumsApp#186]
It looks like we have duplicated code in
/components/FormSubmissionEdit.tsx 
/appBase/components/FormSubmissionEdit.tsx

and in:
/components/QuestionEdit.tsx
/appBase/components/QuestionEdit.tsx

They're not completely identical, but close enough we shouldn't have two copies of these.  Carefully remove the ones in the chums project and keep the appBase copies.  It's used in /components/AssociatedForms, which appears on the person edit screen.

**Comment by pranavmalvawala** [comment]
resolved in https://github.com/LiveChurchSolutions/ChumsApp/pull/201 https://github.com/LiveChurchSolutions/ChumsApp/pull/202
