### ISSUE TITLE
Lake City CC Forms Issues 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChumsApp#189]
I had created forms in the past on chums - looks like they aren’t there any more. I made a new baptism one today that simply said - “Have you been baptized” then clicked yes and save. When I went to click on baptism form it wants me to edit the form - answer the question again - but what I want to see is the answer. Am I doing something wrong?

I’ve created forms again but it’s not keeping my answers to the questions. For example, Have you been baptized - yes - click save. Then I want to go back to see the answer and it doesn’t show - but has me answer the question again.

**Comment by jzongker** [comment]
This was due to malformed data on the forms table.  Archived field was added after these forms were created, but was not populated for older data.  It's working now and only affected Lake City.
