### ISSUE TITLE
Anniversary date issue

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/ChumsApp#19]
'On the people screen, dates of anniversaries displayed there are not the same as the date shown on the “People Edit” screen.'

**Comment by pranavmalvawala** [comment]
I think what you mean is, why does 1/1/1970 show up when user hasn't even selected any Anniversary date. I've sorted it in the following PR. Now Anniversary date would only be show when user selects  option other than "Single".

**Comment by pranavmalvawala** [comment]
Changes are deployed. Let me know if I misunderstood it and it needs correction. @jzongker

**Comment by pranavmalvawala** [comment]
Fixed by https://github.com/LiveChurchSolutions/ChumsApp/pull/37
