### ISSUE TITLE
Dashboard > My Groups is stuck in loading

### ISSUE THREAD

**Issue by luisagloria** [LiveChurchSolutions/ChumsApp#191]
#### Issue description
Dashboard > My Groups is stuck in loading in Chums App

#### Prerequisites
URL: https://app.staging.chums.org/
Browser: Chrome
User: cypress.test@chums.org
Password: password

#### Steps to reproduce the issue

1.  Login using the given credentials in the prerequisites above
2. Click Cypress Chums on the popup dialog
3. Go to Dashboard

#### What's the expected result?
The Page should load without any issues
-

#### What's the actual result?
My Groups is stuck in loading
-

#### Additional details / screenshot
![image](https://user-images.githubusercontent.com/101709075/179398696-b6e7d1b3-895e-4a9f-9dd1-7c72305b1466.png)

**Comment by jzongker** [comment]
This was also due to deactivating the Cypress Test user. It should be working now.  https://github.com/LiveChurchSolutions/AppBase/issues/158 will provide the permanent fix.

**Comment by luisagloria** [comment]
Reopened the ticket as the issue is reproducible again
![image](https://user-images.githubusercontent.com/101709075/180641758-b565edf2-f265-4998-a9a8-2acc2ac95a96.png)

**Comment by jzongker** [comment]
Both this error and #192 were caused by there not being a Person record associated with the User.  The person was deleted.  I've added error handling code to the login page to reactivate deleted Person records if necessary when a User logs in.
