### ISSUE TITLE
Saving changes on People > Personal Details are not working

### ISSUE THREAD

**Issue by luisagloria** [LiveChurchSolutions/ChumsApp#192]
#### Issue description
Saving changes on People > Personal Details are not working

#### Prerequisites
URL: https://app.staging.chums.org/
Browser: Chrome
User: cypress.test@chums.org
Password: password

#### Steps to reproduce the issue

1.  Login using the given credentials in the prerequisites above
2. Click Cypress Chums on the popup dialog
3. Go to People
4. Select a person to edit
5. Click the Personal Details edit icon
6. Update personal details of person
7. Click Save Button

#### What's the expected result?
Changes should save without any issues
-

#### What's the actual result?
Clicking the Save button does nothing
-

#### Additional details / screenshot
![image](https://user-images.githubusercontent.com/101709075/179502271-bdde8e58-1833-4b9e-bb9b-e719f60f4bc0.png)

**Comment by jzongker** [comment]
Was due to cypress user person record being removed.  Adding another issue to gracefully handle this scenario

**Comment by luisagloria** [comment]
Issue still persistent per checking
![image](https://user-images.githubusercontent.com/101709075/180641711-a5b894a3-82c1-46aa-bedc-d5b3b9c73a9e.png)

**Comment by jzongker** [comment]
Was resolved with #191
