### ISSUE TITLE
Clicking the Merge Button in People > Merge Records Pane redirects to login screen

### ISSUE THREAD

**Issue by luisagloria** [LiveChurchSolutions/ChumsApp#194]
#### Issue description
Merging a Person in People page redirects the page to login

#### Prerequisites
URL: https://app.staging.chums.org/
Browser: Chrome
User: cypress.test@chums.org
Password: password

#### Steps to reproduce the issue

1.  Login using the given credentials in the prerequisites above
2. Click Cypress Chums on the popup dialog
3. Go to the People Tab
4. Select any name in People pane to edit
5. Select the Edit button in Personal Details pane
![image](https://user-images.githubusercontent.com/101709075/180642392-813f3787-939b-455e-ac7f-9414846b6588.png)
6. Click Merge
7. Search for a person in Merge Records pane
8. Click the Merge button beside the name

#### What's the expected result?
Person should be merged
-

#### What's the actual result?
Clicking the Merge Button in People > Merge Records Pane redirects to login screen
-

![image](https://user-images.githubusercontent.com/101709075/180642459-0a84f2ee-1162-450c-acf6-3bdca78e41d2.png)

**Comment by jzongker** [comment]
Resolved by @sydorT with https://github.com/LiveChurchSolutions/ChumsApp/commit/11b6a967c014373c1df982af170a97aeb0f5767d
