### ISSUE TITLE
 undefined people in my chums account

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChumsApp#196]
Some older accounts seem to randomly get users added to them they are called  undefined

**Comment by jzongker** [comment]
I've marked all 'undefined' users and removed for now.  Waiting to see if they continue to show up.

**Comment by jzongker** [comment]
This was being caused by MembershipApi/people/claim - The B1 app was passing an empty user account to this api, and the api was creating a new user with empty data to go with that user account.  I updated both the API to check for this and the B1 App to not pass a null user.
