### ISSUE TITLE
Putting Dates in one date they do not show up as the same date when saved 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChumsApp#197]
When I put my anniversary 4/10/10. Click save and then it shows 4/9/10
![image5](https://user-images.githubusercontent.com/65249159/180891816-6a48939d-0e34-4372-9645-2e42a8aac3aa.jpeg)
![image4](https://user-images.githubusercontent.com/65249159/180891818-fda2af0f-e8dc-485a-9a97-73fb62cee1eb.jpeg)

**Comment by jzongker** [comment]
Fixed in https://github.com/LiveChurchSolutions/ChumsApp/commit/800ab2831af60a6a36dd2988db3d90acbc909b47
