### ISSUE TITLE
Make sure pages look good with no data

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/ChumsApp#2]
Several of the pages are blank and look broken when there is no data yet.  Go through the app and make sure they all look nice after the initial registration.  Add messages if necessary ("Attendance chart will appear once attendance has been added.") instead of "no data" type messages.

**Comment by pranavmalvawala** [comment]
Almost, There is just one change that I had in mind, I'll make it and close off.

**Comment by pranavmalvawala** [comment]
Person page - notes section - instead of showing seconds ago besides a notes, show a proper time format
