### ISSUE TITLE
Wedding date bug

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/ChumsApp#20]
From user: 'When no wedding date nor divorce date has been entered in the “People Edit” screen, then the blank results in a date still being displayed. So, it’s a bogus date.'

**Comment by pranavmalvawala** [comment]
You mean Anniversary date right?

**Comment by pranavmalvawala** [comment]
FIxed by https://github.com/LiveChurchSolutions/ChumsApp/pull/37

Yep, got the confirmation it is the same date
