### ISSUE TITLE
Profile link Not going anywhere 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChumsApp#204]
Made a new account in chums when I click on the profile link nothing happens. 
<img width="1494" alt="Screen Shot 2022-09-20 at 10 37 23 AM" src="https://user-images.githubusercontent.com/65249159/191288223-934295e6-3ba7-4bd9-a093-444d6229e267.png">

**Comment by PhotoPaul** [comment]
All external links (including the profile link) on the user menu were not working.

A fix has been pushed and seems to work fine on staging:
https://github.com/LiveChurchSolutions/AppBase/commit/ad025256f6d97ecede0eac79fbc8e6b00ec8d6c5

**Comment by pranavmalvawala** [comment]
Verified! Nicely done @PhotoPaul!
