### ISSUE TITLE
Can not select second Service in chums 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChumsApp#207]
A video is the best way to describe this trying to select second service and I can not. 

chelseaboldt.venture@gmail.com is waiting to continue with her setup

https://user-images.githubusercontent.com/65249159/192891196-0f0a874c-e128-4aa6-8fdd-1497f3beb7d6.mp4

**Comment by jzongker** [comment]
This is fixed now
