### ISSUE TITLE
Increase text field size

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/ChumsApp#31]
The following fields are not large enough to display typical values.  Re-arrange the layout of this form as needed to provide more space to the fields.

![fields](https://user-images.githubusercontent.com/1447203/112742310-22924180-8f53-11eb-81bf-c844560ccb0f.png)

**Comment by pranavmalvawala** [comment]
There was not enough space to increase just the width of inputs without cutting other parts, that's why I have update a layout a bit, I'm sure you'll like it! It looks fine on mobile too. It is more or less looks like a full page form.

**Comment by pranavmalvawala** [comment]
FIxed by https://github.com/LiveChurchSolutions/ChumsApp/pull/38
