### ISSUE TITLE
Enter credit card option doesn't appear if no existing donations

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/ChumsApp#58]
If there is no donation history for a user this message is shown and the option to enter a credit card or bank account is missing.

![image](https://user-images.githubusercontent.com/1447203/119603768-75ea0a00-bdb3-11eb-8c84-c5d01d313321.png)

**Comment by tec7z7** [comment]
Is there a payment gateway setup? It won't show the option to add a payment method unless there is an existing gateway saved.
