### ISSUE TITLE
Wrong donations amounts showing on person page

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/ChumsApp#62]
When a person gives to multiple funds in a single donation, the values reported on the donation summary list on the profile page are wrong.

Example: Total of $20 donated, split between two funds
![image](https://user-images.githubusercontent.com/1447203/119606241-d54a1900-bdb7-11eb-8480-7b3e7423bf1c.png)

Profile page shows two $20 donations.  Show the value from fundDonations instead of donations table.
![image](https://user-images.githubusercontent.com/1447203/119606326-00cd0380-bdb8-11eb-8b90-9ae60bcefbb9.png)

**Comment by tec7z7** [comment]
Fixed in https://github.com/LiveChurchSolutions/ChumsApp/pull/117
