### ISSUE TITLE
notes: a "br" tag shows up if one has pressed enter while creating it 

### ISSUE THREAD

**Issue by pranavmalvawala** [LiveChurchSolutions/ChumsApp#82]
Currently the only tag I know of is "br" but check for rest of the tags as well.

![Capture](https://user-images.githubusercontent.com/42204892/122706510-b84d1c80-d275-11eb-95ce-a6bed0167575.PNG)

**Comment by jzongker** [comment]
What do you think of allowing markdown in the notes field?  This would handle the line breaks well and some additional basic formatting.  LessonsApp is using https://www.npmjs.com/package/react-markdown for this.

**Comment by pranavmalvawala** [comment]
Sure we can add it, I got no problem in that but I'm thinking notes are just notes, most of users would just be leaving a simple note and not expect text formatting I'm sure markdown would be playing important role in lessonApp but I feel we don't need it here just yet. 

Sorry about that, I'm just making sure we are not adding functionalities that's not a need yet. I intend to keep the app slim and straight up do what it's expected to do. Let me know what you think...
