### ISSUE TITLE
Image change should get reflected at all places

### ISSUE THREAD

**Issue by pranavmalvawala** [LiveChurchSolutions/ChumsApp#85]
When I update the image of the logged in user's person record changes are not reflected until refresh.

expected: Image should be updated in navbar and notes section at the very moment. refresh should not be required

**Comment by jzongker** [comment]
The people list appends ?dt=########## to the end of each photo with the last modified timestamp, to work as a cache buster.  This just needs to be applied to all other places that show person photos.

**Comment by matt2695** [comment]
This appears to be a state issue, looks like all the images are updated with cache buster.

**Comment by jzongker** [comment]
Closed with #171 
The ?dt qs was updated a while back, but a fix was applied to update the navbar photo
